module PreprocessingRules

export stopwords,
       split_unigrams,
       collapsed_prefixes,
       split_suffixes,
       suffix_mappings,
       word_substitutions

#------------
# Stopwords |
#------------

# Note:
# the following words are *not* included in stopwords
# b/c they might be relevant for parsing certain types of phrases
#
# and or both either neither nor with
#  

const stopwords = Set{ASCIIString}([
# general english stopwords
"i", "me", "my", "myself",
"we", "our", "ours", "ourselves", "us",
"you", "your", "yours", "yourself", "yourselves",
"he", "him", "his", "himself",
"she", "her", "hers", "herself",
"it", "its", "itself",
"they", "them", "their", "theirs", "themselves",

"a", "an", "the",
"this", "that", "these", "those",
"what", "which", "who", "whom", "whose",

"but", "if", "because",

"is", "am", "are",
"was", "were", "will",
"be", "been", "being",
"have", "has", "had", "having",
"do", "does", "did", "doing",
"as", "until", "while", "of", "at",
"by", "for", "about",
"against", "between", "through",
"during", "before", "after", "again",
"above", "below", "up", "down", "over", "under",
"to", "from",
"in", "into", "on", "onto",
"out", "off", "further",
"now", "then", "once",
"here", "there",
"when", "where", "why", "how", "however",
"all", "any", "each", "only",
"few", "fewer", "less", "more", "most", "much", "many",
"other", "some", "such",
"no", "not",
"own", "same",
"so", "also", "therefore", "thus",
"than",
"too",
"very",
"can", "cannot",
"just",
"still",
"may", "might",
"yet",

"could",
"should",
"would",

# nouns
"advances",
"assumption", "assumptions",
"application", "applications",
"aspect", "aspects",
"article", "articles",
"candidate", "candidates",
"challenge", "challenges",
"copyright", "c", "rights",
"correlation", "correlations",
"elsevier",
"enhancement", "enhancements",
"everyday",
"evidence",
"implication", "implications",
"importance",
"improvement", "improvements",
"innovation", "innovations",
"insight", "insights",
"institute",
"literature",
"magnitude",
"paper", "papers",
"progress",
"research",
"society",
"study", "studies",
"works", # "work" omitted

# verbs
"allow", "allows", "allowed", "allowing",
"appear", "appears", "appeared", "appearing",
"arise", "arises", "arose", "arising",
"behave", "behaves", "behaved", "behaving",
"compare", "compares", "compared", "comparing",
"consist", "consists", "consisted", "consisting",
"contain", "contains", "contained", "containing",
"correlate", "correlates", "correlated", "correlating",
"decrease", "decreases", "decreased", "decreasing",
"demonstrate", "demonstrates", "demonstrated", "demonstrating",
"depend", "depends", "depended", "depending",
"develop", "develops", "developed", "developing",
"differ", "differs", "differed", "differing",
"elucidate", "elucidates", "elucidated", "elucidation",
"employ", "employs", "employed", "employing",
"enable", "enables", "enabled", "enabling",
"enhance", "enhances", "enhanced", "enhancing",
"ensure", "ensures", "ensured", "ensuring",
"evaluate", "evaluates", "evaluated", "evaluating",
"exhibit", "exhibits", "exhibited", "exhibiting",
"find", "finds", "found", "finding", "findings",
"follow", "follows", "followed", "following",
"give", "gives", "gave", "giving",
"govern", "governs", "governed", "governing",
"help", "helps", "helped", "helping",
"highlight", "highlights", "highlighted", "highlighting",
"illustrate", "illustrates", "illustrated", "illustrating",
"imply", "implies", "implied", "implying",
"improve", "improves", "improved", "improving",
"increase", "increases", "increased", "increasing",
"investigate", "investigates", "investigated", "investigating",
"involve", "involves", "involved", "involving",
"lack", "lacks", "lacked", "lacking",
"lower", "lowers", "lowered", "lowering",
"make", "makes", "made", "making",
"mitigate", "mitigates", "mitigated", "mitigating",
"need", "needs", "needed", "needing",
"perform", "performs", "performed", "performing",
"permit", "permits", "permitted", "permitting",
"proceed", "proceeds", "proceeded", "proceeding",
"predict", "predicts", "predicted", "predicting",
"produce", "produces", "produced", "producing",
"prove", "proves", "proved", "proving",
"provide", "provides", "provided", "providing",
"publish", "publishes", "published", "publishing",
"see", "sees", "seen", "seeing",
"seem", "seems", "seemed", "seeming",
"show", "shows", "showed", "showing",
"study", "studies", "studies", "studying",
"suffer", "suffers", "suffered", "suffering",
"suggest", "suggests", "suggested", "suggestion",
"take", "takes", "took", "taking",
"tend", "tends", "tended", "tending",
"raise", "raises", "raised", "raising",
"reduce", "reduces", # "reduced" and "reducing" omitted
"remain", "remains", "remained", "remaining",
"require", "requires", "required", "requiring",
"reveal", "reveals", "revealed",
"underly", "underlies", "underlying",
"use", "used", "using",

# adjectives and adverbs
"good", "better", "best",
"great", "excellent", "fantastic",
"bad", "worse", "worst",
"poor", "terrible",
"effectively", "ineffective", "ineffectively", # "effective" ommitted, c.f. "effective medium theory"
"efficient", "efficiently", "inefficient", "inefficiently",
"substantial", "substantially",
"considerable", "considerably",
"overwhelming", "overwhelmingly",
"extraordinary", "extraordinarily",
"complete", "completely",
"total", "totally",
"entire", "entirely",
"minimal", "minimally",
"simply", # "simple" omitted
"prepare", "prepared", "preparing",
"succeed", "succeeds", "succeeded", "successfully",
"achieve", "achieves", "achieved", "achieving",
"obtain", "obtains", "obtaining",
"result", "results", "resulting",
"namely", "notably",
"particular", "particularly",
"remarkable", "remarkably",
"essential", "essentially",
"consequently", "furthermore",
"demonstratable", "demonstratably",
"truly",
"practically",
"highly", # "high" omitted
"slight", "slightly", "somewhat",
"explicit", "explicitly", "implicit", "implicitly",
"quantitative", "quantitatively", "qualitative", "qualitatively",
"primary", "primarily", "secondary", "secondarily",
"possible", "possibly", "possibilities", "potentially",
"easy", "easily",
"difficult", "difficulty",
"challenging",
"favorable", "favourable", "unfavorable", "unfavourable",
"past", "previously", "prior",
"present", "presently", "recent", "recently", "currently", # "current", "contemporary" omitted
"future",
"promising",
"novel",
"innovative",
"exemplarily",
"along",
"experimental",
"important",
"average",
"ahead", "behind",
"finally", "hence", "times",
"slowly", "quickly",
"shorter", "longer",
"briefly", "gradually",
"having",
"range", "ranging",
"technological",
"evident",
"versatile",
"powerful",
"extremely",
"numerous",
"so-called",
"as-prepared",
"least",
"towards",
"new",
"mainly",
"mostly",
"almost",
"hardly",
"known",
"higher",
"initially",
"based",
"etc",
"enough",
"as-grown",
"instead",
"close", "closely",
"far",
"next", 
"cursory",
"other",
"fair", "fairly",
"different",
"conveniently",
"dramatic", "dramatically",
"rather",
"alongside", "tuned", "occur", "occurs",
"important", "technologically", "sufficiently",
"detailed",
"especially",
"like", "likely",
"equivalently",
"various",
"due",
"significant", "significantly",
"sufficient", "sufficiently",
"strongly",
"approximate",
"relatively",
"subsequent", "subsequently",

# prepositions
"per",
"upon",
"vs",
"within",
"without",

# cardinal numbers
"one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
"eleven", "twelve", "thirteen", "fourteen", "fifteen",
"sixteen", "seventeen", "eighteen", "nineteen", "twenty",

# scientific units
"nm", "um", "mm", "cm", "m", "km",
"nanometer", "micrometer", "millimeter", "meter", "metre", "kilometer", "kilometre",
"ng", "ug", "mg", "cg", "g", "kg",
"gram", "kilogram", "ton", "tons",
"ns", "us", "ms", "s", "hr", "yr",
"second", "seconds", "minute", "minutes", "hour", "hours",
"day", "days", "week", "weeks", "month", "months", "year", "years",
"nA", "uA", "mA", "A", "kA", "MA", "GA",
"ampere", "amperes",
"nJ", "uJ", "mJ", "J", "kJ", "MJ", "GJ", "TJ",
"joule", "joules",
"nW", "uW", "mW", "W", "kW", "MW", "GW",
"watt", "watts",
"nV", "uV", "mV", "V", "kV", "MV", "GV",
"volt", "volts",
"nF", "uF", "mF", "F", "kF", "mF", "GF",
"farad", "farads",
"ohm", "ohms",
"nT", "uT", "mT", "T", "tesla", "gauss",
"Hz", "kHz", "MHz", "GHz", "THz",
"hertz",
"mPa", "Pa", "MPa", "GPa",
"pascals",
"torr",
"rad", "radians", "deg", "degrees",
"C", "F", "K", "centigrade", "fahrenheit", "kelvin",
"mol", "moles",

"cm(-2)", "degreesC",

# other crap
"sci", "phys", "sons",
"et", "via", "viz", "e-g",
"GmbH", "gmbh", "Inc", "inc", "Ltd", "ltd", "LLC", "llc", "AIP",
"B.V", "B.V.", "S.A", "S.A.",
"I-V",
"Elsevier", "John", "Wiley", "Sons",
])

#-------------------
# Hyphenation Rules
#-------------------

const split_unigrams = Set([
"TIPS-pentacene",
"drop-casting",
"hot-wire",
"phase-pure",
"first-principles",
"quantum-chemical",
"multiple-trapping",
"drift-diffusion",
"ray-tracing",
"molecular-dynamics",
"monte-carlo",
"Monte-Carlo",
"least-squares",
"molecular-beam",
"electron-beam",
"close-spaced",
"high-vacuum",
"hot-wall",
"modulated-flux",
"facing-target",
"RF-magnetron",
"DC-magnetron",
"cathodic-arc",
"pulsed-laser",
"glow-discharge",
"thin-film",
])

const collapsed_prefixes = Set([
"co",
"un",
"non",
"anti",
"pre",
"post",
"photo",
"nano"
])

const split_suffixes = Set([
"Based",
"based",
"rich",
"type",
"like",
"phase",
"coupling",
"casting",
"induced",
"assisted",
"enhanced",
"beam",
"thermal",
"layer",
"deposited",
"temperature",
"functionalized",
"doped",
"doping",
"coated",
])

#-------------------
# Substitution Rules
#-------------------

const suffix_mappings = (ASCIIString => ASCIIString)[
    "ivate" => "ivation",
    "ivated" => "ivation",
    "orate" => "oration",
    "orated" => "oration",
    "rized" => "rization",
    "inized" => "inization",
]

const word_substitutions = (ASCIIString => ASCIIString)[

# [misc terms]

"X-ray" => "x-ray",
"X-Ray" => "x-ray",
"characterisation" => "characterization",

# we can't parse ALLCAPS titles well,
# so manually doing some substitutions from the lowercased stuff here

"cigs" => "CIGS",
"cigse" => "CIGS",
"cigsse" => "CIGSSe",
"czts" => "CZTS",
"cztse" => "CZTSe",
"cztsse" => "CZTSSe",
"cis" => "CIS",
"cise" => "CISe",
"cisse" => "CISSe",
"cdte" => "CdTe",
"n-cdte" => "n-CdTe",
"p-cdte" => "p-CdTe",
"znte" => "ZnTe",
"sno2" => "SnO2",
"ito" => "ITO",
"fto" => "FTO",
"zno" => "ZnO",
"azo" => "AZO",
"bzo" => "BZO",
"izo" => "IZO",
"gzo" => "GZO",
"gaas" => "GaAs",
"cds" => "CdS",
"CUINSE2" => "CuInSe2",

"pcbm" => "PCBM",
"cvd" => "CVD",
"pecvd" => "PECVD",
"vhf-pecvd" => "VHF-PECVD",
"mocvd" => "MOCVD",
"ap-mocvd" => "AP-MOCVD",
"lp-mocvd" => "LP-MOCVD",
"hw-cvd" => "HW-CVD",
"cat-cvd" => "Cat-CVD",
"aacvd" => "AACVD",
"rtcvd" => "RT-CVD",
"rt-cvd" => "RT-CVD",
"ecr-cvd" => "ECR-CVD",
"afm" => "AFM",
"hrtem" => "HRTEM",
"pixe" => "PIXE",
"ftir" => "FTIR",

# [substance terms]

"vapour" => "vapor",
"vapours" => "vapors",
"sulphide" => "sulfide",

# [material terms]

"polymer-fullerene" => "polymer:fullerene",
"Polymer:Fullerene" => "polymer:fullerene",
"nano-ink" => "nanoink",
"polymeric" => "polymer",
"covered" => "coated",
"polysulphide" => "polysulfide",
"nanotubular" => "nanotube",
"multicrystalline" => "polycrystalline",
"structure-type" => "structure",
"structured" => "structure",
"hierarchically" => "hierarchical",
"photoanode" => "anode",
"photocathode" => "cathode",
"photoelectrode" => "electrode",
"single-wall" => "single-walled",
"multi-wall" => "multi-walled",
"zincblende" => "sphalerite",
"morphologies" => "morphology",
"nondoped" => "undoped",

# [synthesis terms]

"sputter" => "sputtering",
"annealed" => "annealing",
"postannealed" => "annealing",
"postannealing" => "annealing",
"nonannealed" => "unannealed",
"annealing-free" => "unannealed",
"electroplating" => "electrodeposition",
"pulse" => "pulsed",
"facilely" => "facile",
"Stille-coupling" => "stille-coupling",
"chemisorbed" => "chemisorption",
"sulphurization" => "sulferization",
"sulphurisation" => "sulferization",
"sulfuration" => "sulferization",
"sulfidation" => "sulferization",
"self-assembled" => "self-assembly",
"template-directed" => "template-assisted",
"LbL" => "LBL",

"annealed" => "annealing",
"postannealed" => "annealing",
"postannealing" => "annealing",
"nonannealed" => "unannealed",
"annealing-free" => "unannealed",

"rf" => "RF",
"r.f." => "RF",
"radiofrequency" => "RF",
"dc" => "DC",
"d.c." => "DC",
"directcurrent" => "DC",

# [measurement terms]

"microscope" => "microscopy",
"spectrometer" => "spectroscopy",
"diffractometer" => "diffraction",
"diffractometry" => "diffraction",
"spectrometry" => "spectroscopy",
"spectrophotometer" => "spectrophotometry",

#"raman" => "Raman",
"Micro-Raman" => "micro-raman",
"mu-Raman" => "micro-raman",
"mu-raman" => "micro-raman",
#"Micro-Raman" => "micro-Raman",
#"mu-Raman" => "micro-Raman",
"infra-red" => "infrared",

"ultraviolet" => "uv",
"UV" => "uv",
"UV-vis" => "uv-vis",
"UV-Vis" => "uv-vis",
"UV-visible" => "uv-vis",
"UV-Visible" => "uv-vis",
"UV/vis" => "uv-vis",
"ultraviolet-visible" => "uv-vis",
"UVVIS" => "uv-vis",
"UVVis" => "uv-vis",
"UV-vis-NIR" => "uv-vis-nir",
"UV-Vis-NIR" => "uv-vis-nir",
"UV/Vis/NIR" => "uv-vis-nir",

# [property terms]

"absorbance" => "absorption",
"spectrum" => "spectra",
"transporting" => "transport",
"transportation" => "transport",
"excitonic" => "exciton",
"velocities" => "velocity",
"mobilities" => "mobility",
"processes" => "process",
"resistances" => "resistance",
"physico-chemical" => "phyiscochemical",
"densities" => "density",
"efficiencies" => "efficiency",
"valance" => "valence",
"energies" => "energy",
"collecting" => "collection",
"collector" => "collection",
"frequencies" => "frequency",
#"schottky" => "Schottky",

# [model terms]

"modeling" => "model",
"modelling" => "model",
"simulator" => "simulation",
"numerically" => "numerical",
"First-principles" => "first-principles",
"AMPS" => "AMPS-1D",
"approaches" => "approach",
]

end
